/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelgui;
import javax.swing.JOptionPane;
/**
 *
 * @author PikeMobile
 */
public class CreateUser extends javax.swing.JDialog {

    private UserInformation user = null;
    private int accountType ;
    /**
     * Creates new form CreateUser
     */
    public CreateUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountTypeBox = new javax.swing.JComboBox();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        confirmTextField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createUserButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        accountTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Customer", "Employee", "Admin" }));
        accountTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeBoxActionPerformed(evt);
            }
        });

        firstNameTextField.setName("First Name"); // NOI18N

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Email Address");

        jLabel4.setText("Password");

        jLabel5.setText("Confirm");

        jLabel6.setText("Account Type");

        createUserButton.setText("Create User");
        createUserButton.setName("Create User"); // NOI18N
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmTextField)
                            .addComponent(passwordTextField)
                            .addComponent(firstNameTextField)
                            .addComponent(lastNameTextField)
                            .addComponent(emailTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createUserButton)
                        .addGap(38, 38, 38)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserButton)
                    .addComponent(clearButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeBoxActionPerformed
        // TODO add your handling code here:
        accountType = accountTypeBox.getItemCount();
    }//GEN-LAST:event_accountTypeBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        this.clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void clearFields()
    {
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        emailTextField.setText(null);
        passwordTextField.setText(null);
        confirmTextField.setText(null);
    }
    
    private String convertAccountType()
    {
        switch(accountType)
        {
            case 0:
                return "Customer";
            case 1:
                return "Employee";
            case 2:
                return "Admin";
            default:
                return null;        
        }
    }
    
    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
        //String FirstName, String LastName, String Password, String EmailAddress, String AccountType
        if(firstNameTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Error!\nPlease insert a valid Name.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(lastNameTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Error!\nPlease insert a valid Name.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(emailTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Error!\nPlease insert a valid Email.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            SQLiteJDBC database = SQLiteJDBC.getInstance();
            if(createUserButton.getName().equals("Update"))
            {
                //user.SetPassword(emailTextField.getText());
                if(user.updatePassword(passwordTextField.getText()))//database.updatePassword(user))
                {
                    this.dispose();
                }
            }
            else
            {
                user = new UserInformation(firstNameTextField.getText(), lastNameTextField.getText(), 
                            passwordTextField.getText(), emailTextField.getText(), convertAccountType());
                System.out.println("Adding new User...");
                System.out.println("First name: " + firstNameTextField.getText() +
                                   "\nLast Name: " + lastNameTextField.getText() + 
                                   "\nPassword: " + passwordTextField.getText()+ 
                                   "\nEmail: " + emailTextField.getText()+ 
                                   "\nAccount Type: " + convertAccountType() +
                                    "\n");
                    if(database.insert("USERS", user))
                    {
                        this.clearFields();
                        this.setVisible(false);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "This username has already been taken.\nPlease Select another.");
                    }
            }
        }
        
    }//GEN-LAST:event_createUserButtonActionPerformed
    
    /**
     * 
     */
    public void setFields(UserInformation aUser)
    {
        user = aUser;
        accountTypeBox.setSelectedIndex(2);
        this.lockAccountType();
        firstNameTextField.setText(user.GetFirstName());
        lastNameTextField.setText(user.GetLastName());
        emailTextField.setText(user.GetEmailAddress());
        accountTypeBox.setEnabled(false);
        firstNameTextField.setEnabled(false);
        lastNameTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        createUserButton.setText("Update");
        clearButton.setEnabled(false);
        createUserButton.setName("Update");
    }
    
    /**
     * Lock the Option to change account types
     */
    public void lockAccountType()
    {
        accountTypeBox.setEnabled(false);
    }
    
    /**
     * Lock the Option to change account types
     */
    public void unlockAccountType()
    {
        accountTypeBox.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateUser dialog = new CreateUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountTypeBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JPasswordField confirmTextField;
    private javax.swing.JButton createUserButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPasswordField passwordTextField;
    // End of variables declaration//GEN-END:variables
}
